# Google Cloud Build Configuration file
# https://cloud.google.com/build/docs/build-config-file-schema
# https://cloud.google.com/build/docs/building/build-containers
# https://github.com/GoogleCloudPlatform/cloud-builders
steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "$_IMAGE_NAME", "."]
# Running `docker push` manually ensures the image is pushed _before_ deploying.
# However, not using the built in `images` config key alters the final build
# summary output: the image name is omitted.
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "$_IMAGE_NAME"]
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "$_SERVICE_NAME"
    - "--image"
    - "$_IMAGE_NAME"
    - "--region"
    - "$_REGION"
serviceAccount: "projects/$PROJECT_ID/serviceAccounts/cloud-build-service-account@js185-todo-app.iam.gserviceaccount.com"
substitutions:
  _ARTIFACT_REPO: "cloud-build"
  _IMAGE_NAME: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}-image:${SHORT_SHA}"
  _REGION: "us-central1"
  _SERVICE_NAME: "${PROJECT_ID}"
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  dynamicSubstitutions: true
